-- BobsToolbox Change Log
-- The change log lists changes of particular note to users, not every change made.
--
--4.3.0.3
-- Started working on Warlock rotation frame.
-- Started working on rogue rotation frame.
-- Added extra power frame.
-- Added vampiric embrace to the missing buff frame for priest.
-- Minor changes to the priest rotation frame.
--
--4.0.3.6
-- Added the missing buff frame.
-- Modified the priest rotation frame.
--
--4.0.3.4
-- Added player and target castbar frames.
-- Reset all configuration that is older than 4.0 version because of incompatibility.
-- Reintroduced the rotation frame with better support for paladins, mages and priest.
--
--4.0.2.8
-- Added much better support for frame layout.
-- Added moving handles to all movable frames.
-- Total redesign on the group frame to support templates.
-- Rewrote most of the addon for better performance.
-- Added templates for unit button.
-- Added casting bar to player and target frame.
-- Restructured configuration settings.
--
--3.4.0.6
-- Added support for watching for missing buffs.
-- Added unit power frame.
-- Fixed frames from being able to go off screen.
--
--3.2.6.8
-- Added arcane mage to rotation frame.
-- Modified to be sure you are only looking for your buffs for rotation frame.
-- Changes priest to show mind blast as available if Empowered Shadow is up and greater than 8 seconds.
-- Cleaned up handling of blizzard frames. 
-- Added target casting bar.
--
--3.2.6.0
-- Added feature to invert health display for group frame.
-- Added shaman spells.
-- Show debuffs for all classes.
-- Increased aggro notification overlay for better visibility.
--
--3.2.4.10
-- Fixed problem with moving raid frames.
-- Fixed issue with stack overflow.
-- Added feature to turn off custom cast bar.
--
--3.2.2.6
-- Added threat number to player frame.
-- Add more detail threat colors to group frame.
-- Added sorting group in horizontal or vertical rows.
-- Fixed minimap button organize function.
--
--3.2.0.8
-- Total rewrite. Remove lots but added lots.
-- Update TOC for patch 4.2.0.
--
--2.6.4.10
-- Updated TOC for patch 4.1.0.
--
--2.6.4.8
-- Added individual settings for active and missing buffs.
-- Fixed a bug in the active and missing buff icons.
--
--2.6.4.2
-- Minor bug fixes.
--
--2.4.4.8
-- Added extra power bar for priest, warlocks, rogues and paladins.
-- Fixed bug in the minimap icon.
--
--2.2.4.2
-- Minor layout changes.
-- Added DPS rotation frame (only supports priest, atm).
--
--2.0.4.6
-- Refactored settings tables. Now the settings infrastructure is simpler.
-- Fixed minimap icon from resetting everytime the settings load.
-- Many other changes but I didn't document them well. I'm coding like crazy. :)
--
--2.0.2.6
-- Cataclysmic reboot of BobsToolbox...
-- Many changes but I had to remove some items like raid frames and the buff bars. Hopefully I can add them back.
--
--1.8.8.4
-- Added the PvP frame to monitor honor points, arena points and arena rating.
-- Added threat monitoring feature to the player frame.
-- Added locking feature to anchors. You can now manually move the frames around.

--1.8.6.2
-- Fixed the players health / mana bar when dead. The bars are now hidden if you are dead.
-- Fixed the color gradient from green (100%) to red (0%).
-- Fixed frames sizing of empty frames. Now frames will propertly collapse as expected.
-- Fixed unprotected frames that have protected frames anchored to them. The were causing taint issues when trying to resize during combat.
-- Fixed frame levels for all forms.
-- Updated: Reimplemented the profiles option. Still has issue for you cannot copy profiles from other characters.
-- Fixed weapon buff icon problem in buff frame where any buff at location 16 would look for a weapon buff.
-- Added role icon to party and raid frame.
-- Added raid status icons to party and raid frame.
-- Added readycheck monitoring feature. Now when a readycheck occurs you will see the status on the party and raid frame. Must be raid leader or assistant to view the results.
-- Changed to only show the weakened soul exclamation mark to priest only. No one else would be interested.
-- Added Paladin's Blessing of Kings as main missing buff.
-- Added poison and magic detection for Paladins.
-- Added golden exclamation for weakened soul debuff for priest.
-- Added font styling for the party, pet and raid frames.
-- Added the cooldown frame.

--1.2.8.6
-- Changed the maximums for the X/Y offsets to 800/-800 up from 400/-400.
-- Changed the maximum for button width to 300 up from 200.

-- 1.2.6.14
-- Fixed bug in commands /btb toggleraid, toggleparty, toggletot.
-- Fixed sizing bug in the debuff frame.
-- Updated LibHealComm to 1.6.2 up from 1.5.3.
-- Updated Ace 3.0 framework to r907 up from r879.

-- 1.2.6.10
-- Added custom zone profiles. Use "/btb addzone" and "/btb clearzone" to add and remove custom profile for the current zone. Great for Battlegrounds, arenas and raids.
-- Fixed bug in buff frame that would not correctly tooltip buffs in a certain state.
-- Added the buff frame to the debuff frame's "anchor to" list.

-- 1.2.4.12
-- Fixed an issue where the bars would not be the correct size base on state of the frames. 
-- Added more "Anchor To" points to many frames.
-- Added the capability of hiding the minimap button.
-- Added the new buff / debuff frame.
-- Moved minimap icon settings to global settings. Now minimap icon settings changes should persist.

-- 1.0.2.10
-- Fixed bug in the "unhiding" of the blizzard player frame target.
-- Fixed tooltips NPC, Player Pets, and Non-combat pets.
-- Updates some of the default values.
-- Removed the spell for range checking for player frame. We will use the range spells defined in the heal and damage button.
-- Removed extra rez information from pet frame.

-- 1.0.0.2
--
-- Finally BobsToolbox is official "released" as in file type "release". :) 
-- Fixed the HideWhenSolo feature for the Raid and Pet frame. 
-- Removed "group" option for RaidFrame. All bars will be grouped by their "group" by default. 

-- 0.9.8.12
--
-- Moved the raid and pet frame to Blizzard template. This re-leaves BobsToolbox from a lot of work. Some features are broke like hide when solo. I plan on implementing these in the next version. 
-- Added support for druid spell and debuff feature (colored bars). 
-- Many small bug fixes and other changes I forgot to write down. 

-- 0.9.2.16
--
-- Removed profiles until I can better support them. 
-- Fixed the /reset command. Now the /reset will reset the current settings for that spec. 
-- Added Damage Button settings. Now both the Target of Target and the focus frame will use the appropriate setting depending on the target. If the target is friendly then the heal button settings will be used. If the target is unfriendly then the damage button settings will be used. 
-- Added the new Focus Frame. Just target something then type "/focus". You can also bind a key to "focus target". 
-- Added "Hide Focus Frame" to Blizzard frame settings. This will hide the default UI focus frame. 
-- Fixed the player bars from initially hide when [hide @ 100%] is turned off. 

-- 0.8.2.4
--
-- Fixed the raid / pet frame anchor point setting. 
-- Move the Target of Target button into its own frame. 
-- Added many features to the Target of Target frame. 
-- Fixed a resource bug that would have cause serious performance hit when modifying many settings. 

-- 0.7.5.6
--
-- Added buttons on the main configuration screen to help with navigation to other settings. 
-- Added header to Raid and Pet settings dialog to seperate anchoring & position settings. 
-- Added support to offset Player, Target and Pet bars. This should also fix the scale issue as you can now better position the bars. I will continue to look for a more elegant solution. 

-- 0.7.4.8
--
-- Fixed an issue with the command "toggleraid". 
-- Fixed anchoring issues with the pet frame. 

-- 0.7.3.2
--
-- Initial Release.